server:
  port: 8082

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/SaidNurmatov/microservice-cloud-server.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "SaidNurmatov"
          password: ${GIT_KEY}