spring:
  cloud:
    config:
      uri: http://service-loadbalancer-config:8082  # ConfigServer portu (look yml file)

  config:
    import: "configserver:"
  application:
    name: aut-application  # path data yml AuthMicroservice